before_script:
  - export PY_EXE=python3.5
  - pip3 install -r requirements.txt
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - systemctl stop django-markdown


stages:
  - deploy

runapp:
  stage: deploy
  script:
    - export PY_EXE=python3.5 
    - systemctl start django-markdown
