before_script:
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate

stages:
  - deploy

runapp:
  stage: deploy
  script:
    - python manage.py runserver