image: python:3.5
before_script:
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate
  - systemctl stop django-markdown


stages:
  - deploy

runapp:
  stage: deploy
  script:
    - systemctl start django-markdown
