# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='markup.Category'),
            preserve_default=False,
        ),
    ]
